CREATE DATABASE `shareposts`CHARACTER SET utf8 COLLATE utf8_hungarian_ci;

CREATE TABLE shareposts.users (
id INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR (255),
email VARCHAR (255),
PASSWORD VARCHAR (255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (id)
) CHARSET = utf8 COLLATE = utf8_hungarian_ci;

CREATE TABLE shareposts.posts (
id INT NOT NULL AUTO_INCREMENT,
user_id INT,
title VARCHAR(255),
BODY TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
) CHARSET=utf8 COLLATE=utf8_hungarian_ci;
